import string

def vig_decrypt(ciphertext, key):
    A = string.ascii_uppercase
    out = []
    ki = 0
    for c in ciphertext:
        if c in A:
            shift = (A.index(c) - A.index(key[ki % len(key)].upper())) % 26
            out.append(A[shift])
            ki += 1
        else:
            out.append(c)
    return "".join(out)

ciphertext = "ZCZCOIBLSQYFVMYIWPZPYSXDCJZOJXDYHZKAHIWQFVYIWEIVCNVASBUOEZWJIZXTADYHZDVWPFOKIBYWPSFPSINGBXKAHEYANBVXELUKYNWOSFVIBYPFOKDUEPGGWKEJNMAKRRGWQSVFRREDWKGRVAWCLGVPHIBFGGLWRCKRRVHCGJCPVQNICYHWXSGZXRWOKSEKEISGZCSAKPMSOZYSERWEQNRUYBUKYPELJVXGMKLGNSGLJMDRIZIJRTFBGLAMFZQVRWRCIKAHSCFVWNMJWCLBFYNCGKQHENYBKORSBBIVBRGKKDVXFINCBVQBXEYHZXTSQPRVKYAEJZFXYCOJCNYHVLPCXBRWOYBUSSSPFSICTIPUWENBJPFWJYCTKPHLXVXUWCLBVWGJCJSAKATSIIGLELUPYHLWTSEOTSPGOKOQAERVLCVXEQCWDUIDGUYOFXEKDFBGEJASKRNXSCQFXPPQBSKRVWOROXOBJKSFTYYPWZCIKGMKLOJAHMYIZPKFTKQGZLYIUMIYKIIPMZUEFXDYHUSFTHYBESAKPMAVOGAERVKRRTNCGZNRRPQCFXNRZMBTOUIDYGRCFYNYBTOGLWRHYOTSRCFEWRRPQIGZBVPQVZCCPWLHYSAKOUWCVZSRCJVBLUQGQBVLMYYBEYGTNMAZCRXKFCCNZCELJVCGSNQHFQRXDCFZPGLAWHYSAOPFSZBVRPCFVCGWWPSSOGXAPGVBIIZCZJOJLAPSJYJMJLWEQGLAGFWSEQYMADSGQALHEYJMOGBRVYSQPWEDRVAQHJSGMOAFLMVEHRVRDLSQYBUSPSJTWEMRXDCAFPGLATOCERSBRVZCCVKNSIDLEJBMFENVAZSJDCPWASUDBEYOIZBRXDCSMSQIJASWYEYOGIIQRCKSHFLRKXMFIYJSNQHVKYEYMBTVHWETSUOZSJQHIKGMKLCWDUIRYZLOBJPFSGBBHQAHFBGSLPCMSQIWDICVRVZCGTBVTPGCEYSXDCDCYGMJMFUOEXDYHZMNRBGBRVYCLCFJENHAKMWBVIJBGKYPSIKWKDBFWAYZXTYOWCLBFEJVWFEFPUKCCSAENM"  # full ciphertext
key = "NEWYORK"
plaintext = vig_decrypt(ciphertext.replace(" ", "").upper(), key)
print(plaintext)
